# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WalkWithMe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'React', path: '../node_modules/react-native', :subspecs => [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket'
    ]

    pod 'GoogleMaps'

  target 'WalkWithMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
